<?php

/** @var Escaper $escaper */
/** @var FinalPriceBox $block */
/** @var Index $index */
/** @var PriceInterface $priceModel */
/** @var Template $block */

use Magento\Catalog\Pricing\Render\FinalPriceBox;
use Magento\Framework\Escaper;
use Magento\Framework\Pricing\Price\PriceInterface;
use Magento\Framework\View\Element\Template;
use Serwach\OmnibusExtension\Block\Index;

$priceModel = $block->getPriceType('regular_price');
/** @var PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() === 'item_view') ? true : false;
$index = $block->getLayout()->createBlock(Index::class);
$price = $historicalPrice = $specialPrice = 0;
$type = "";

if ($index->getProduct() !== null) {
    $price = $index->getProduct()->getData('regular_price') ?? 0;
    $historicalPrice = $index->getProduct()->getData('historical_price') ?? 0;
    $specialPrice = $index->getProduct()->getData('special_price') ?? 0;
    $type = $index->getProduct()->getTypeId();
}
?>
<?php if ($specialPrice) :?>
    <span class="serwach-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => '',
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
<?php else :?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>
